--[[

    Please do NOT edit this file.
    The contents of this file will be generated automatically.
    
]]--
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "enUS", true);

L["BINDING_NAME_ADT_OPTIONS_DLG"]                  = 'Options Dialog'
